version: "3"
services:
  auth_service:
    build: ./AuthService/app
    ports:
      - "50001:50001"
    environment:
      - AUTH_PORT=50001
      - AUTH_HOST=auth_service
      - DB_HOST=db
      - PYTHONPATH=AuthService/app
    networks:
      - grpc_network

  article_service:
    build: ./ArticleService/app
    ports:
      - "50002:50002"
    environment:
      - ARTICLE_PORT=50002
      - AUTH_HOST=auth_service
      - AUTH_PORT=50001
      - DB_HOST=db
      - PYTHONPATH=ArticleService/app
    networks:
      - grpc_network
    depends_on:
      - auth_service
      - db

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "5001:3306"
    networks:
      - grpc_network
    command: --default-authentication-plugin=mysql_native_password

networks:
  grpc_network:
    driver: bridge

volumes:
  db-data:
